services:
  - type: web
    name: telegram-media-transcriber
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install poetry && poetry install
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    plan: free